import React, { ReactNode, FC } from "react";
import Footer from "../components/Footer/Footer";
import Head from "next/head";
import { Body } from "./styled";

type Props = {
  backgroundColor?: string;
  header?: ReactNode;
  children?: ReactNode;
};

const Layout: FC<Props> = ({ header, children, backgroundColor }) => {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body backgroundColor={backgroundColor}>{header}</Body>
      {children}
      <Body backgroundColor={backgroundColor}>
        <Footer />
      </Body>
    </>
  );
};

export default Layout;
